---
- name: configure gunicorn
  template:
    src: '{{ gunicorn_conf_tpl }}'
    dest: '{{ gunicorn_conf_path }}'
  notify: reload app

- name: configure supervisor
  template:
    src: '{{ supervisor_conf_tpl }}'
    dest: '{{ supervisor_config_dir }}/{{ program_name }}.conf'
  notify:
    - reload supervisor config
    - reload app
  become: true
  tags: superuser
  when: supervisor_use_sudo

- name: configure supervisor
  template:
    src: '{{ supervisor_conf_tpl }}'
    dest: '{{ supervisor_config_dir }}/{{ program_name }}.conf'
  notify:
    - reload supervisor config
    - reload app
  when: not supervisor_use_sudo
